// Edit this file to add, remove, reorder, or replace blocks.
// Upload artwork into public/art/, then reference it here as "/art/file-name.ext".

export const cover = {
  title: 'From The Mezzanine',
  image: '/art/cover-ellie-joan.png',
  alt: 'From The Mezzanine cover artwork by Ellie Joan',
};

export const contents = {
  title: 'Table of Contents',
  image: '/art/table-of-contents-landscape-v2.png',
  hoverImagePrefix: '/art/toc-hover-v2-',
  alt: 'Landscape table of contents for From The Mezzanine',
  pageCount: 2,
  links: [
    { title: 'Introduction', targetId: 'introduction', side: 'left', row: 0 },
    { title: 'Epigenetics Egg & Spoon Race', targetId: 'epigenetics-egg-spoon-race', side: 'left', row: 1 },
    { title: 'Parasitic Sentience', targetId: 'epigenetics-extension', side: 'left', row: 2 },
    { title: 'Warm Anchors', targetId: 'warm-anchors', side: 'left', row: 3 },
    { title: 'But We Were Beautiful', targetId: 'but-we-were-beautiful', side: 'left', row: 4 },
    { title: 'Lament A La Wet Cement', targetId: 'lament-wet-cement', side: 'left', row: 5 },
    { title: 'Why Are The Mayflies Marching', targetId: 'why-are-mayflies-marching', side: 'left', row: 6 },
    { title: 'Not Sure But Forward And Fast', targetId: 'not-sure-forward-fast', side: 'left', row: 7 },
    { title: 'Salute The Living Dust', targetId: 'salute-living-dust', side: 'left', row: 8 },
    { title: 'E.L', targetId: 'el-old-empire', side: 'left', row: 9 },
    { title: 'Flower Assets', targetId: 'flower-assets', side: 'left', row: 10 },
    { title: 'Slaves To Us Too', targetId: 'slaves-to-us-too', side: 'left', row: 11 },
    { title: 'The Ants', targetId: 'the-ants', side: 'left', row: 12 },
    { title: 'Expired Treaty', targetId: 'expired-treaty', side: 'left', row: 13 },
    { title: 'Sum Of Us', targetId: 'expired-treaty-window', side: 'left', row: 14 },
    { title: 'Window In The Fog', targetId: 'window-in-the-fog', side: 'left', row: 15 },
    { title: 'Derobe For The Stars', targetId: 'derobe-for-the-stars', side: 'right', row: 0 },
    { title: 'Celestial Caesar', targetId: 'celestial-caesar', side: 'right', row: 1 },
    { title: 'Loyal Metronome', targetId: 'loyal-metronome', side: 'right', row: 2 },
    { title: 'Oh Wise One', targetId: 'oh-wise-one', side: 'right', row: 3 },
    { title: 'Surprise Pity Party', targetId: 'petals-despite-it-all', side: 'right', row: 4 },
    { title: 'Worn Out Velvet', targetId: 'worn-out-velvet', side: 'right', row: 5 },
    { title: 'Faux Fucks In Big Lights', targetId: 'faux-fucks-big-light', side: 'right', row: 6 },
    { title: 'Iris Diner', targetId: 'this-diner', side: 'right', row: 7 },
    { title: 'Cerebral Warehouse', targetId: 'faceless-facades', side: 'right', row: 8 },
    { title: 'Pick Axes And Putty And Advice', targetId: 'pick-axes-putty-advice', side: 'right', row: 9 },
    { title: 'Quantum Entanglement X Faded Love', targetId: 'quantum-entanglement-faded-love', side: 'right', row: 10 },
    { title: 'Can People Change?', targetId: 'can-people-change', side: 'right', row: 11 },
    { title: 'I Set Sail', targetId: 'i-set-sail', side: 'right', row: 12 },
    { title: 'My Sighs Are Light', targetId: 'my-sighs-are-light', side: 'right', row: 13 },
    { title: 'Rubiks Cube Raft', targetId: 'rubiks-cube-raft', side: 'right', row: 14 },
    { title: 'From The Mezzanine', targetId: 'from-the-mezzanine-closing', side: 'right', row: 15 },
  ],
};

export const blocks = [
  {
    id: 'introduction',
    type: 'spread',
    title: 'Introduction',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/introduction-01-left.png',
      imageAlt: 'Introduction spread page 1',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/introduction-01-right.png',
      imageAlt: 'Introduction spread page 2',
    },
  },
  {
    id: 'introduction-continued',
    type: 'spread',
    title: 'Introduction Continued',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/introduction-02-left.png',
      imageAlt: 'Introduction spread page 3',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/introduction-02-right.png',
      imageAlt: 'Introduction spread page 4',
    },
  },
  {
    id: 'introduction-visual',
    type: 'spread',
    title: 'Introduction Visual',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/introduction-03-left.png',
      imageAlt: 'Introduction spread page 5',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/introduction-03-right.png',
      imageAlt: 'Introduction visual page',
    },
  },
  {
    id: 'introduction-atoms',
    type: 'spread',
    title: 'Introduction Atoms',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/introduction-04-left.png',
      imageAlt: 'Introduction spread page with text about atoms',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/introduction-04-right.png',
      imageAlt: 'Introduction visual page with suspended ceramic artworks',
    },
  },
  {
    id: 'epigenetics-egg-spoon-race',
    type: 'spread',
    title: 'Epigenetics Egg & Spoon Race',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-01-left.png',
      imageAlt: 'Epigenetics egg and spoon race text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-01-right.png',
      imageAlt: 'Repeated photo studio street image grid',
    },
  },
  {
    id: 'epigenetics-extension',
    type: 'spread',
    title: 'Epigenetics Extension',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-02-left-v2.png',
      imageAlt: 'Epigenetics extension text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-02-right.png',
      imageAlt: 'Epigenetics layered artwork page',
    },
  },
  {
    id: 'epigenetics-space-form',
    type: 'spread',
    title: 'Epigenetics Space Form',
    tone: 'soft-white-shadow',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-03-left-v4.png',
      imageAlt: 'Epigenetics page with figure and dotted path',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-03-right-v2.png',
      imageAlt: 'Epigenetics shape and space page',
    },
  },
  {
    id: 'epigenetics-sound-song',
    type: 'spread',
    title: 'Epigenetics Sound Song',
    tone: 'soft-white-shadow',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-04-left-v2.png',
      imageAlt: 'Epigenetics shape and space page repeated',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-04-right-v2.png',
      imageAlt: 'Epigenetics sound and song page',
    },
  },
  {
    id: 'epigenetics-sapien-space',
    type: 'spread',
    title: 'Epigenetics Sapien Space',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-05-left.png',
      imageAlt: 'Epigenetics sapien shape page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-05-right-v2.png',
      imageAlt: 'Epigenetics rose garden page',
    },
  },
  {
    id: 'warm-anchors',
    type: 'spread',
    title: 'Warm Anchors',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-06-left.png',
      imageAlt: 'Warm anchors text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/epigenetics-06-right.png',
      imageAlt: 'Warm anchors abstract artwork page',
    },
  },
  {
    id: 'but-we-were-beautiful',
    type: 'spread',
    title: 'But We Were Beautiful',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/beautiful-01-left.png',
      imageAlt: 'But we were beautiful text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/beautiful-01-right.png',
      imageAlt: 'But we were beautiful abstract artwork page',
    },
  },
  {
    id: 'lament-wet-cement',
    type: 'spread',
    title: 'Lament a la Wet Cement',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/lament-01-left.png',
      imageAlt: 'Lament a la wet cement text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/lament-01-right.png',
      imageAlt: 'Lament a la wet cement continuation text page',
    },
  },
  {
    id: 'why-are-mayflies-marching',
    type: 'spread',
    title: 'Why Are the Mayflies Marching',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/mayflies-01-left.png',
      imageAlt: 'Why are the mayflies marching text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/mayflies-01-right.png',
      imageAlt: 'Why are the mayflies marching mayfly image page',
    },
  },
  {
    id: 'not-sure-forward-fast',
    type: 'spread',
    title: 'Not Sure, But Forward and Fast',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/forward-fast-02-right.png',
      imageAlt: 'Not sure but forward and fast text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/forward-fast-01-left.png',
      imageAlt: 'Not sure but forward and fast circuit board artwork page',
    },
  },
  {
    id: 'butcher-baker-candlestick-maker',
    type: 'spread',
    title: 'The Butcher, The Baker, The Candlestick Maker',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/butcher-baker-01-left.png',
      imageAlt: 'The butcher the baker the candlestick maker artwork page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/butcher-baker-01-right.png',
      imageAlt: 'The bank teller and fortune tellers artwork page',
    },
  },
  {
    id: 'tender-street-sweeper',
    type: 'spread',
    title: 'Tender and the Midnight Street Sweeper',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/tender-street-01-left.png',
      imageAlt: 'Tender fiscal tender artwork page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/tender-street-01-right.png',
      imageAlt: 'Midnight street sweeper artwork page',
    },
  },
  {
    id: 'preacher-lepers',
    type: 'spread',
    title: 'The Preacher and the Lepers',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/preacher-lepers-01-left.png',
      imageAlt: 'The preacher in threadbare robes artwork page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/preacher-lepers-01-right.png',
      imageAlt: 'The lame and the lepers artwork page',
    },
  },
  {
    id: 'old-men-living-relics',
    type: 'spread',
    title: 'Old Men and Living Relics',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/old-men-relics-01-left.png',
      imageAlt: 'Old men with their oaths and codes artwork page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/old-men-relics-01-right.png',
      imageAlt: 'Living relics and living dust artwork page',
    },
  },
  {
    id: 'salute-living-dust',
    type: 'spread',
    title: 'Salute the Living Dust',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/salute-living-dust-01-left.png',
      imageAlt: 'Salute the living dust text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/salute-living-dust-01-right.png',
      imageAlt: 'Living dust futures diagram page',
    },
  },
  {
    id: 'el-old-empire',
    type: 'spread',
    title: 'E, L',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/el-old-empire-01-left.png',
      imageAlt: 'E L old empire cafe text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/el-old-empire-01-right.png',
      imageAlt: 'E L cafe conversation continuation page',
    },
  },
  {
    id: 'el-music-resistance',
    type: 'spread',
    title: 'E, L Music and Resistance',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/el-music-resistance-01-left.png',
      imageAlt: 'E L music hope and resistance text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/el-music-resistance-01-right.png',
      imageAlt: 'E L resistance and humble service continuation page',
    },
  },
  {
    id: 'flower-assets',
    type: 'spread',
    title: 'Flower Assets',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/flower-assets-01-left.png',
      imageAlt: 'Flower assets text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/flower-assets-01-right.png',
      imageAlt: 'Flower assets rose continuation page',
    },
  },
  {
    id: 'slaves-to-us-too',
    type: 'spread',
    title: 'Slaves To Us Too',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/slaves-to-us-too-01-left.png',
      imageAlt: 'Painted window grid artwork page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/slaves-to-us-too-01-right.png',
      imageAlt: 'Slaves to us too text page',
    },
  },
  {
    id: 'the-ants',
    type: 'spread',
    title: 'The Ants',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/the-ants-01-left.png',
      imageAlt: 'The ants text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/the-ants-02-right.png',
      imageAlt: 'Ant algebra artwork page',
    },
  },
  {
    id: 'expired-treaty',
    type: 'spread',
    title: 'Expired Treaty',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/expired-treaty-01-left.png',
      imageAlt: 'Expired treaty text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/expired-treaty-01-right.png',
      imageAlt: 'Expired treaty continuation page',
    },
  },
  {
    id: 'expired-treaty-window',
    type: 'spread',
    title: 'Expired Treaty Window',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/expired-treaty-window-02-left.png',
      imageAlt: 'Cafe window with plants and candle artwork page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/expired-treaty-window-01-right.png',
      imageAlt: 'Jester card artwork page',
    },
  },
  {
    id: 'sum-of-us',
    type: 'spread',
    title: 'Sum of Us',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/sum-of-us-01-left.png',
      imageAlt: 'Sum of us text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/sum-of-us-01-right.png',
      imageAlt: 'Sum of us continuation text page',
    },
  },
  {
    id: 'window-in-the-fog',
    type: 'spread',
    title: 'Window in the Fog',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/window-fog-01-left.png',
      imageAlt: 'Window in the fog text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/window-fog-01-right.png',
      imageAlt: 'Window in the fog collage artwork page',
    },
  },
  {
    id: 'derobe-for-the-stars',
    type: 'spread',
    title: 'Derobe for the Stars',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/derobe-stars-01-left.png',
      imageAlt: 'Red abstract artwork page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/derobe-stars-01-right.png',
      imageAlt: 'Derobe for the stars text page',
    },
  },
  {
    id: 'celestial-caesar',
    type: 'spread',
    title: 'Celestial Caesar',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/celestial-caesar-01-left.png',
      imageAlt: 'Celestial caesar text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/celestial-caesar-01-right.png',
      imageAlt: 'Celestial caesar continuation page',
    },
  },
  {
    id: 'loyal-metronome',
    type: 'spread',
    title: 'Loyal Metronome',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/loyal-metronome-01-left.png',
      imageAlt: 'Loyal metronome text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/loyal-metronome-03-right.png',
      imageAlt: 'Loyal metronome continuation page',
    },
  },
  {
    id: 'loyal-metronome-continued',
    type: 'spread',
    title: 'Loyal Metronome Continued',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/loyal-metronome-02-left.png',
      imageAlt: 'Loyal metronome continuation text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/loyal-metronome-02-right.png',
      imageAlt: 'Coastal sea view artwork page',
    },
  },
  {
    id: 'oh-wise-one',
    type: 'spread',
    title: 'Oh Wise One',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/catalogue-01-left.png',
      imageAlt: 'Catalogue artwork page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/oh-wise-one-01-right.png',
      imageAlt: 'Oh wise one text page',
    },
  },
  {
    id: 'worn-out-velvet',
    type: 'spread',
    title: 'Worn Out Velvet',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/worn-out-velvet-01-left.png',
      imageAlt: 'Worn out velvet text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/worn-out-velvet-01-right.png',
      imageAlt: 'Worn out velvet artwork page with repeated figure and grey shapes',
    },
  },
  {
    id: 'this-diner',
    type: 'spread',
    title: 'This Diner',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/this-diner-01-left.png',
      imageAlt: 'Ceramic pond artwork page with flame, flowers, figure, and suspended form',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/this-diner-01-right.png',
      imageAlt: 'This diner text page',
    },
  },
  {
    id: 'faux-fucks-big-light',
    type: 'spread',
    title: 'Faux Fucks in Big Light',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/faux-fucks-big-light-02-right.png',
      imageAlt: 'Faux fucks in big light artwork page with ceramic eyes and heart forms',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/faux-fucks-big-light-01-left.png',
      imageAlt: 'Faux fucks in big light text page',
    },
  },
  {
    id: 'petals-despite-it-all',
    type: 'spread',
    title: 'Petals, Despite It All',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/petals-despite-it-all-01-left.png',
      imageAlt: 'Petals, despite it all text page beginning with the inquisitor beckoned me closer',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/petals-despite-it-all-01-right.png',
      imageAlt: 'Petals, despite it all continuation text page',
    },
  },
  {
    id: 'faceless-facades',
    type: 'spread',
    title: 'Faceless Facades',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/faceless-facades-02-left.png',
      imageAlt: 'Cerebral warehouse text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/faceless-facades-01-right.png',
      imageAlt: 'Collage artwork page with doorway, telephone, hanging lamp, figures, and pink flowers',
    },
  },
  {
    id: 'pick-axes-putty-advice',
    type: 'spread',
    title: 'They Come With Their Pick Axes',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/pick-axes-putty-advice-01-left.png',
      imageAlt: 'Abstract painted artwork page with blue, red, cream, and dark forms',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/pick-axes-putty-advice-01-right.png',
      imageAlt: 'They come with their pick axes, and putty and advice text page',
    },
  },
  {
    id: 'quantum-entanglement-faded-love',
    type: 'spread',
    title: 'Quantum Entanglement x Faded Love',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/quantum-entanglement-faded-love-01-left.png',
      imageAlt: 'Quantum entanglement x faded love text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/quantum-entanglement-faded-love-01-right.png',
      imageAlt: 'Quantum entanglement x faded love continuation text page',
    },
  },
  {
    id: 'can-people-change',
    type: 'spread',
    title: 'Can People Change?',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/can-people-change-01-left.png',
      imageAlt: 'Can people change text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/can-people-change-01-right.png',
      imageAlt: 'Batumi artwork page with waterfall, framed symbol, brown field, and sea',
    },
  },
  {
    id: 'i-set-sail',
    type: 'spread',
    title: 'I Set Sail',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/i-set-sail-01-left.png',
      imageAlt: 'I set sail text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/i-set-sail-02-right.png',
      imageAlt: 'I set sail artwork page with figures over a compass-like red texture',
    },
  },
  {
    id: 'my-sighs-are-light',
    type: 'spread',
    title: 'My Sighs Are Light',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/my-sighs-are-light-01-left.png',
      imageAlt: 'Blue and cream swirling abstract artwork page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/my-sighs-are-light-01-right.png',
      imageAlt: 'My sighs are light text page',
    },
  },
  {
    id: 'rubiks-cube-raft',
    type: 'spread',
    title: 'Rubiks Cube Raft',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/rubiks-cube-raft-01-left.png',
      imageAlt: 'Color-block painted artwork page with pale figures and blue, red, green, and black panels',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/rubiks-cube-raft-01-right.png',
      imageAlt: 'Rubiks cube raft text page',
    },
  },
  {
    id: 'striped-vessel',
    type: 'spread',
    title: 'Striped Vessel',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/striped-vessel-01-left.png',
      imageAlt: 'Front view of a striped sculptural vessel with eye and wire flowers',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/striped-vessel-01-right.png',
      imageAlt: 'Back view of a striped sculptural vessel with wire flower forms',
    },
  },
  {
    id: 'from-the-mezzanine-closing',
    type: 'spread',
    title: 'From the Mezzanine',
    showTitle: false,
    leftPage: {
      variant: 'transparent-image',
      image: '/art/from-the-mezzanine-closing-01-left.png',
      imageAlt: 'From the mezzanine text page',
    },
    rightPage: {
      variant: 'transparent-image',
      image: '/art/from-the-mezzanine-closing-02-right.png',
      imageAlt: 'From the mezzanine closing mark page',
    },
  },
];
